### PR TITLE
Refactorization of mountainprocess

### PR DESCRIPTION
**Pull request by wysota**
Mountainprocess still needs to be refactored but maybe within a separate task.

### CODE REVIEW

**Comment by magland** [comment]
There has been some dev on master2 on these files in the last day or so, so I 'd like to merge your changes into master2 instead. How shall we do this?

**Comment by wysota** [comment]
Sorry, haven't seen your comment. I think you should try cherry-picking my commit into the branch and then manually re-apply your modifications. You may have to revert your commit first, cherry pick mine and then cherry pick yours and solve the conflicts manually using meld or kdiff3 (or whatever else you use). Shouldn't be that hard because I didn't modify your code that much, I mostly moved chunks of it around.

**Comment by magland** [comment]
This particular situation is too difficult for me. I've made a lot of changes recently. Could you base new stuff off of 0.9.1-dev please? There were a bunch of important changes today.

**Comment by wysota** [comment]
Are we completely abandoning master?

**Comment by magland** [comment]
Right now the default branch is 0.9.1-dev. I was planning to abandon
master. Do you have any objection?

**Comment by wysota** [comment]
Usually master contains a bleeding edge version and you create release branches off master, stabilize them, release and port needed changes back to master.

**Comment by magland** [comment]
Thanks for explaining that. That makes a lot of sense. It's funny, master always had a different meaning to me, but that's because I haven't really experienced stable vs. bleeding edge, because the bleeding edge usually has had fewer problems than older versions.

Anyway, I will sync master=0.9.1-dev next time I get a chance. Once I have a code with minimal loose ends, I will call it 0.9.1, and then master will be synced with 0.9.2-dev. Sound okay?

**Comment by wysota** [comment]
Sure. I will try to incorporate changes from this pull request into 0.9.1-dev

**Comment by magland** [comment]
I just merged 0.9.1-dev into master, so for the moment those to are equal.
Now I can't decide whether to start pushing to master and periodically
merge into 0.9.1-dev or do the opposite.

**Comment by wysota** [comment]
Replaced by https://github.com/magland/mountainlab/pull/107

**Pull request closed without merging**
