### PR TITLE
Fixed comp issues

### PR DESCRIPTION
**Pull request by alexmorley**
Not sure if this is where you would like to have it included though.

### CODE REVIEW

**Comment by alexmorley** [comment]
Error below.

Replicated error and fix on clean clone of repo on another (fedora 25) machine.



```
g++ -c -pipe -fopenmp -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../mlcommon/include -I../../../mlcommon/include/cachemanager -I../../../mlcommon/include/componentmanager -I../../../mlcommon/include/mda -I../../../mountainsort/src/isosplit5 -I../../../mountainsort/src/utils -I../../../../Qt/5.8/gcc_64/include -I../../../../Qt/5.8/gcc_64/include/QtNetwork -I../../../../Qt/5.8/gcc_64/include/QtCore -I../build -I../../../../Qt/5.8/gcc_64/mkspecs/linux-g++ -o ../build/p_sort_clips.o p_sort_clips.cpp
g++ -c -pipe -fopenmp -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../mlcommon/include -I../../../mlcommon/include/cachemanager -I../../../mlcommon/include/componentmanager -I../../../mlcommon/include/mda -I../../../mountainsort/src/isosplit5 -I../../../mountainsort/src/utils -I../../../../Qt/5.8/gcc_64/include -I../../../../Qt/5.8/gcc_64/include/QtNetwork -I../../../../Qt/5.8/gcc_64/include/QtCore -I../build -I../../../../Qt/5.8/gcc_64/mkspecs/linux-g++ -o ../build/p_consolidate_clusters.o p_consolidate_clusters.cpp
g++ -c -pipe -fopenmp -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../mlcommon/include -I../../../mlcommon/include/cachemanager -I../../../mlcommon/include/componentmanager -I../../../mlcommon/include/mda -I../../../mountainsort/src/isosplit5 -I../../../mountainsort/src/utils -I../../../../Qt/5.8/gcc_64/include -I../../../../Qt/5.8/gcc_64/include/QtNetwork -I../../../../Qt/5.8/gcc_64/include/QtCore -I../build -I../../../../Qt/5.8/gcc_64/mkspecs/linux-g++ -o ../build/p_create_firings.o p_create_firings.cpp
g++ -c -pipe -fopenmp -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../mlcommon/include -I../../../mlcommon/include/cachemanager -I../../../mlcommon/include/componentmanager -I../../../mlcommon/include/mda -I../../../mountainsort/src/isosplit5 -I../../../mountainsort/src/utils -I../../../../Qt/5.8/gcc_64/include -I../../../../Qt/5.8/gcc_64/include/QtNetwork -I../../../../Qt/5.8/gcc_64/include/QtCore -I../build -I../../../../Qt/5.8/gcc_64/mkspecs/linux-g++ -o ../build/p_combine_firings.o p_combine_firings.cpp
g++ -c -pipe -fopenmp -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../mlcommon/include -I../../../mlcommon/include/cachemanager -I../../../mlcommon/include/componentmanager -I../../../mlcommon/include/mda -I../../../mountainsort/src/isosplit5 -I../../../mountainsort/src/utils -I../../../../Qt/5.8/gcc_64/include -I../../../../Qt/5.8/gcc_64/include/QtNetwork -I../../../../Qt/5.8/gcc_64/include/QtCore -I../build -I../../../../Qt/5.8/gcc_64/mkspecs/linux-g++ -o ../build/p_fit_stage.o p_fit_stage.cpp
p_detect_events.cpp: In function ‘bool p_detect_events(QString, QString, P_detect_events_opts)’:
p_detect_events.cpp:34:35: error: ‘fabs’ was not declared in this scope
                     val = fabs(val);
                                   ^
p_detect_events.cpp: In function ‘QVector<double> P_detect_events::detect_events(const QVector<double>&, double, double, int)’:
p_detect_events.cpp:79:27: error: ‘fabs’ was not declared in this scope
             val = fabs(val);
                           ^
p_detect_events.cpp: In function ‘double P_detect_events::pseudorandomnumber(double)’:
p_detect_events.cpp:109:31: error: ‘cos’ was not declared in this scope
     double ret = sin(i + cos(i));
                               ^
p_detect_events.cpp:109:32: error: ‘sin’ was not declared in this scope
     double ret = sin(i + cos(i));
                                ^
Makefile.mountainsort2:1094: recipe for target '../build/p_detect_events.o' failed
make[1]: *** [../build/p_detect_events.o] Error 1
make[1]: *** Waiting for unfinished jobs....
p_consolidate_clusters.cpp: In function ‘bool P_consolidate_clusters::should_use_template(const Mda32&, Consolidate_clusters_opts)’:
p_consolidate_clusters.cpp:126:27: error: ‘fabs’ was not declared in this scope
             if (fabs(value) > abs_peak_val) {
                           ^
p_consolidate_clusters.cpp:134:33: error: ‘fabs’ was not declared in this scope
     if (fabs(abs_peak_ind - Tmid) > peak_location_tolerance) {
                                 ^
Makefile.mountainsort2:1253: recipe for target '../build/p_consolidate_clusters.o' failed
make[1]: *** [../build/p_consolidate_clusters.o] Error 1
make[1]: Leaving directory '/home/data/mountainlab/packages/mountainsort2/src'
Makefile:526: recipe for target 'sub-packages-mountainsort2-src-mountainsort2-pro-make_first-ordered' failed
make: *** [sub-packages-mountainsort2-src-mountainsort2-pro-make_first-ordered] Error 2
Problem in compilation.

```

**Comment by wysota** [comment]
Okay then. Since we're using c++, #include <cmath> seems more appropriate but math.h is acceptable too.

**Comment by alexmorley** [comment]
could change to `<cmath>` but @magland is going to add the <math.h> in another commit.

**Comment by wysota** [comment]
I know, I'm not forcing cmath.

**Pull request closed without merging**
