### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by wysota**
Mostly math optimizations.

Please have a quick look whether I didn't break anything. It's quite late :)

### CODE REVIEW

**Comment by magland** [comment]
There is a problem in get_sort_indices(). The idea is to return the index permutation corresponding to the sorting. 

For example, if the input is [1, 2, 3, 5.5, 4.5, 3.5, 2.5, 1.5], the output should be

[0, 7, 1, 6, 2, 5, 4, 3]

I wasn't that happy with how I ended up doing it, but maybe that was the only way.

**Comment by wysota** [comment]
Ok, now I get it. I'll think about it.

**Comment by wysota** [comment]
Ok, see if it works now.

By the way, while compiling I was getting some linker errors related to Mda32.

**Comment by magland** [comment]
Not quite working. I think you meant to initialize result as an array of integers from 0,1,2,...,X.count()-1.

I am not able to reproduce the linking error. Could you check with the most recent version after a clean, and then send the details?

**Comment by wysota** [comment]
Ah, ok, I forgot to resize the result before calling iota. Should be fine now:

include <vector>
#include <algorithm>
#include <iostream>

int main() {
  std::vector<double> v = { 1, 2, 3, 5.5, 4.5, 3.5, 2.5, 1.5 };
  std::vector<int> result;
  result.resize(v.size());
  std::iota(result.begin(), result.end(), 0);
  std::stable_sort(result.begin(), result.end(), [&v](int i1, int i2) { return v[i1] < v[i2]; });
  for(int i: result)
    std::cout << i << " ";
  std::cout << std::endl;  
  return 0;
}

yields: 0 7 1 6 2 5 4 3

**Comment by wysota** [comment]
Would you check if it works as intended?

**Comment by magland** [comment]
It does not appear to have worked, in that the sorting fails to give the right answer. I will examine more closely.

**Comment by wysota** [comment]
That's really strange. Maybe I have broken one of the other algorithms? Are there unit tests available for them?

**Comment by magland** [comment]
This would be a good time to make unit tests. But there is a possibility I gave you the wrong info. For example, the indices might be the inverse permutation of what it needs to be if that makes sense.

**Comment by wysota** [comment]
I'm getting identical results for both algorithms.

```
#include <vector>
#include <algorithm>
#include <iostream>

struct scs {
  double val;
  long index;
};

struct sc {
  bool operator()(const scs& a, const scs& b) const {
    if (a.val < b.val) return true;
    if (a.val == b.val) return (a.index < b.index);
    return false;
  }
};

int main() {
  std::vector<double> v = { 1, 2.5, 3, 5.5, 4.5, 3.5, 2.5, 1.5 };
  std::vector<int> result;
  for(int i = 0; i < v.size(); ++i) result.push_back(i);
  std::stable_sort(result.begin(), result.end(), [&v](int i1, int i2) { return v[i1] < v[i2]; });
 
  std::vector<scs> list;
  for (int i = 0; i < v.size(); i++) {
    scs tmp;
    tmp.val = v[i];
    tmp.index = i; 
    list.push_back(tmp);
  }
  std::sort(list.begin(), list.end(), sc());
  std::vector<int> result2;
  for(int i = 0; i < list.size(); i++) {
    result2.push_back(list[i].index);   
  }
   
  auto diff = std::mismatch(result.begin(), result.end(), result2.begin());
  if (diff.first == result.end() && diff.second == result2.end()) {
    std::cout << "Results are identical" << std::endl;
  } else {
    std::cout << "Results differ on pos:" << (diff.first-result.begin()) << std::endl;
  }
   
  return 0;
}
```

**Comment by magland** [comment]
Okay. There is probably a red herring. I will look into it, since I can
reproduce the problem on my computer.
J

**Comment by magland** [comment]
I did another test. The problem does not seem to be with get_sorting_indices. So, unless I am making an error elsewhere there is a problem with one of the other optimized routines. It's hard to say which one without re-running the sorting again and again. So maybe you could test them out? If for some reason I am wrong and there is no bug, I apologize in advance. But as far as I can see, something is not right.

**Comment by wysota** [comment]
I'll do the tests. Do we have any specific unit testing approach?

**Comment by magland** [comment]
No I am not good with unit tests. Open to suggestions.

**Comment by wysota** [comment]
I will create a dedicated directory for storing tests, then one directory per module and I will reference particular files directly (thus if you move files, tests will fail to build)

**Comment by magland** [comment]
Sounds good.

**Comment by wysota** [comment]
FYI, there is a unit-tests branch in the repo that contains unit tests for MLCompute. You can have some fun with it if you want and add more tests :)

Using those tests I managed to improve performance of one of the functions (correlation calculation) by order of one magnitude.

**Comment by magland** [comment]
Wow?!

Quick question... did you find a bug that would explain the issue I was
seeing?

**Comment by wysota** [comment]
No, not yet. I have to fill the tests with actual test data. I'll do that tomorrow. I did find one difference - your implementation of dot product returns 0 for empty or different length vectors while STL's inner_product returns 1. I don't know if it might have influenced the results. 

Regarding the optimization of correlation -  I used faster functions, managed to get rid of one pass over each of the vectors and in addition split most computations into two threads so that they run in parallel. There is still place for improvement. 

I also noticed that all those implementations will break for really large data sets or really small input values.

**Comment by wysota** [comment]
I found a couple of bugs using unit tests (yeeey!) and fixed them (yeeey!). It might finally be working now.

**Comment by magland** [comment]
I checked out the optimization branch but something still wasn't working right. (I have to re-run a sorting pipeline every time to test and that's a pain -- will be nice when we get the processor unit tests up and running)

After trying various things, I resorted to just copying and pasting different pieces of your code. As far as I can see everything works, except, for get_sort_indices. That is weird because I thought that was working before. The code looks a bit different from what I remember could you take a look?

**Comment by magland** [comment]
Here's the code: The top function seems different from the bottom. (I should really look into how this works, but have been focusing on other things)

`QList<long> get_sort_indices(const QList<long>& X)
{
    QList<long> result = X;
    std::stable_sort(result.begin(), result.end());
    return result;
}

QList<long> get_sort_indices(const QVector<double>& X)
{
    QList<long> result;
    std::copy(X.constBegin(), X.constEnd(), result.begin());
    std::stable_sort(result.begin(), result.end());
    return result;
}`

**Comment by magland** [comment]
FYI, the status of things right now. I hand pasted your optimized code into master .... all except the get_sort_indices.

**Comment by wysota** [comment]
I'll fix get_sort_indices and issue another pull request.

**Pull request closed without merging**
